theme: jekyll-theme-minimal
title : Rasim Labibov
brandTitle: Rasim Labibov
description: |
  Personal blog and projects of Rasim Labibov. Topics include
   astronomy, graphics, math, and physics.
author :
  name : Rasim Labibov
  github : Postrediori
  twitter : RLabibov
